acd_variables:
  work_with_external_ips: "N"
  work_with_metallb: "N"

# INT01: nginx ingress (ms360-platform-crd) + customer cert SAN airflow.int.corp.amdocs.azr
# For PROD use custom/override-values-prod.yaml
ingress:
  enabled: true
  host: airflow.int.corp.amdocs.azr
  tls:
    secretName: airflow-tls

service:
  tcpports:
    type: ClusterIP

service_annotations:
  global:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "snet-at-a1g-Billing-INT-we-001-Access"
  tcp:
  udp:
